### ISSUE TITLE
Web UI not working correctly.

### ISSUE THREAD

**Issue by FilHarr** [SenexCrenshaw/xTeVe#51]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
The [Tapiosinn/tv-logos](https://github.com/Tapiosinn/tv-logos) repository has been disabled. This causes TVLogosFile.js to throw errors on a fresh install and prevents the web UI from functioning correctly. The settings page does not show any settings and clicking on any channels on the mapping page does not open the pop up.

Error when clicking on a channel is:

```
Uncaught TypeError: Cannot read properties of null (reading 'forEach')
    at TVLogosFile.newTvLogosIdPicker (TVLogosFile.js:29:50)
    at openPopUp (menu_ts.js:1374:72)
    at HTMLTableCellElement.onclick ((index):1:13)
```
and when opening settings page:
```
Uncaught TypeError: Cannot read properties of null (reading 'forEach')
    at TVLogosFile.newTvLogosCountryPicker (TVLogosFile.js:54:50)
    at SettingsCategoryItem.createSettings (settings_ts.js:144:72)
    at settings_ts.js:595:37
    at Array.forEach (<anonymous>)
    at SettingsCategoryItem.createCategory (settings_ts.js:585:14)
    at showSettings (settings_ts.js:608:29)
    at ShowContent.show (menu_ts.js:609:17)
    at openThisMenu (menu_ts.js:779:13)
    at HTMLLIElement.onclick ((index):1:13)
```

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu] - Ubuntu 22.04.01 (running in docker)
- Arch [e.g. Intel 64 Bit] - Intel 64 bit
- xTeVe Version and Build - 2.5.2

**To Reproduce**
1. Create a fresh docker container install
3. Go to web UI
4. Add playlist and XMLTV files
5. Error will be thrown when trying to view settings or select any channels on mapping page.

**Expected behavior**
The web UI to work correctly.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Same error in Chrome, Edge, and Firefox

**Comment by SenexCrenshaw** [comment]
they moved to gitlab. I converted to that.
Fixed in pr #52
